version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.3
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - custom-network

  api:
    container_name: api
    build: 
      context: .
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge

volumes:
  db: